"""empty message

Revision ID: 1ebf572b4ab3
Revises: 88989a1552d1
Create Date: 2025-05-20 15:47:26.126149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebf572b4ab3'
down_revision = '88989a1552d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'system', ['system_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('system_id')

    op.drop_table('system')
    # ### end Alembic commands ###
